resolver: lts-13.13
packages:
- '.'
extra-deps:
    - SDL-0.6.6.0
    - Chart-1.9
    - Chart-diagrams-1.9
    - SVGFonts-1.6.0.3
    - bench-show-0.2.2

flags: {}
extra-package-dbs: []
rebuild-ghc-options: true
# For mac ports installed SDL library on Mac OS X
extra-include-dirs:
- /opt/local/include
